#!/usr/bin/env python3
"""Read src/bridge.js and generate src/bridge_js.bats with C string literal."""

import sys

def main():
    with open("src/bridge.js", "r") as f:
        js_content = f.read()

    lines = js_content.split("\n")
    # Remove trailing empty line if present
    if lines and lines[-1] == "":
        lines = lines[:-1]

    with open("src/bridge_js.bats", "w") as out:
        out.write("(* bridge_js -- GENERATED by generate_bridge_js.py *)\n")
        out.write("(* Do not edit this file -- edit src/bridge.js instead *)\n")
        out.write("\n")
        out.write('#include "share/atspre_staload.hats"\n')
        out.write("\n")
        out.write("staload \"./lib.sats\"\n")
        out.write("\n")
        out.write("$UNSAFE begin\n")
        out.write("%{\n")
        out.write("static const char *_bridge_js_source(void);\n")
        out.write("%}\n")
        out.write("end\n")
        out.write("\n")
        out.write('extern fun _bridge_js_source(): string = "mac#_bridge_js_source"\n')
        out.write("\n")
        out.write("implement produce_bridge() = _bridge_js_source()\n")
        out.write("\n")
        out.write("$UNSAFE begin\n")
        out.write("%{$\n")
        out.write("static const char *_bridge_js_source(void) {\n")
        out.write("  return\n")

        for line in lines:
            # Escape backslashes and quotes for C string
            escaped = line.replace("\\", "\\\\").replace('"', '\\"')
            out.write(f'"{escaped}\\n"\n')

        out.write("  ;\n")
        out.write("}\n")
        out.write("%}\n")
        out.write("end\n")

    print(f"Generated src/bridge_js.bats from {len(lines)} JS lines")

if __name__ == "__main__":
    main()
